<?php
/*
 * Documento   : editarDominio
 * Creado      : 11-jul-2014
 * Autor       : ..... .....
 * Descripcion : 
 */
$editar = Session::getPermiso('MNUACT');

$data = configurarMenuController::getDominio(SimpleForm::getParam('_idDominio'));

?>
<form id="<?php echo T3; ?>formEditarDominio" name="<?php echo T3; ?>formEditarDominio" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true" onclick="configurarMenu.resetKey();">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo M_FE_DOM_TITLTE; ?></h4>
            </div>
            <div class="modal-body smart-form">
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo M_FG_DOM_L_DOM; ?></label>
                        <div class="col col-10">
                            <label class="input"> 
                                <input type="text" id="<?php echo T3; ?>txt_dominio" name="<?php echo T3; ?>txt_dominio" value="<?php echo $data['dominio']; ?>"></input>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo M_FG_DOM_L_ICON; ?></label>
                        <div class="col col-6">
                            <label class="input"> 
                                <input type="text" id="<?php echo T3; ?>txt_icono" name="<?php echo T3; ?>txt_icono" value="<?php echo $data['icon']; ?>"></input>
                            </label>
                        </div>
                        <?php echo Functions::help(M_FG_DOM_H_ICON); ?>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo M_FG_DOM_L_ORD; ?></label>
                        <div class="col col-2">
                            <label class="input"> 
                                <input type="text" id="<?php echo T3; ?>txt_orden" name="<?php echo T3; ?>txt_orden" value="<?php echo $data['orden']; ?>"></input>
                            </label>
                        </div>
                        <?php echo Functions::help(M_FG_DOM_H_ORD); ?>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-2"></label>
                        <div class="col col-3">
                            <label class="checkbox">
                                <input type="checkbox" name="<?php echo T3; ?>chk_activo" id="<?php echo T3; ?>chk_activo" value="1" <?php echo ($data['activo'] == 1)?'checked':''; ?>></input>
                                <i></i>
                                <?php echo CK_ACTIVO; ?>
                            </label>
                        </div>
                    </div>
                </section>
            </div>
            <div class="modal-footer">
                <?php if($editar['permiso']):?>
                <button id="<?php echo T3; ?>btnEditaDominio" type="submit" class="<?php echo $editar['theme']; ?>">
                    <i class="<?php echo $editar['icono']; ?>"></i> <?php echo $editar['accion']; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>" onclick="configurarMenu.resetKey();">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->

<!-- si no riene permiso se anula submit desde cualquier input -->
<?php if(!$editar['permiso']): ?>
<script>
    simpleScript.noSubmit('#<?php echo T3; ?>formEditarDominio');
</script>
<?php endif; ?>
<script>
    $('.xhelp').tooltip({placement:'right'});
    $('#<?php echo T3; ?>formEditarDominio').validate({
        // Rules for form validation
        rules : {
                <?php echo T3; ?>txt_dominio : {
                        required : true,
                        regular: true,
                        minlength: 5
                },
                <?php echo T3; ?>txt_icono : {
                        required : true,
                        regular: true,
                        minlength: 5
                },
                <?php echo T3; ?>txt_orden : {
                        required : true,
                        number: true,
                        maxlength: 2
                }
        },

        // Do not change code below
        errorPlacement : function(error, element) {
                error.insertAfter(element.parent());
        },

        submitHandler: function(){
            configurarMenu.postEditarDominio();
        }   
    });
</script>
</form>