<?php
/*
 * Documento   : indexOpcion
 * Creado      : 09-ago-2014
 * Autor       : ..... .....
 * Descripcion : 
 */

echo Functions::widgetOpen(array(
    'id' => T6,
    'title' => LABEL_10 . SimpleForm::getParam('_modulo'),
    'padding' => true,
    'wizard' => true
));
?>
<div class="row">
    <form id="<?php echo T6; ?>formOpcion" novalidate="novalidate">
        <div id="bootstrap-wizard-1" class="col-sm-12">
            <div class="form-bootstrapWizard">
                <ul class="bootstrapWizard form-wizard">
                    <li class="active" data-target="#step1">
                        <a href="#tab1" data-toggle="tab"> <span class="step">1</span> <span class="title">Información general</span> </a>
                    </li>
                    <li data-target="#step2">
                        <a href="#tab2" data-toggle="tab"> <span class="step">2</span> <span class="title">Formulario</span> </a>
                    </li>
                    <li data-target="#step3">
                        <a href="#tab3" data-toggle="tab"> <span class="step">3</span> <span class="title">Data Grid</span> </a>
                    </li>
                    <li data-target="#step4">
                        <a href="#tab4" data-toggle="tab"> <span class="step">4</span> <span class="title">Crear Opción</span> </a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="tab-content">
                <div class="tab-pane active" id="tab1">
                    <br><br>
                    <h3><strong>Paso 1</strong> - Información general</h3>

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-keyboard-o fa-lg fa-fw"></i></span>
                                    <input class="form-control input-lg" placeholder="<?php echo LABEL_11; ?>" type="text" id="<?php echo T6; ?>txt_opcion" name="<?php echo T6; ?>txt_opcion">
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-keyboard-o fa-lg fa-fw"></i></span>
                                    <input class="form-control input-lg" placeholder="<?php echo LABEL_13; ?>" type="text" id="<?php echo T6; ?>txt_prefijo" name="<?php echo T6; ?>txt_prefijo">
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group smart-form">
                                <div class="inline-group">
                                    <label class="radio"> 
                                        <input type="radio" id="<?php echo T6; ?>rd_tipoB" name="<?php echo T6; ?>rd_tipo" value="B" checked onclick=""> Básica
                                        <i></i>
                                    </label>
                                    <label class="radio"> 
                                        <input type="radio" id="<?php echo T6; ?>rd_tipoM" name="<?php echo T6; ?>rd_tipo" value="M"> Mantenedor
                                        <i></i>
                                    </label>
                                    <label class="radio"> 
                                        <input type="radio" id="<?php echo T6; ?>rd_tipoR" name="<?php echo T6; ?>rd_tipo" value="R"> Reporte
                                        <i></i>
                                    </label>
                                    <?php echo Functions::help(LABEL_12); ?>
                                </div>

                            </div>

                        </div>
                    </div>

                </div>







                <div class="tab-pane" id="tab2">
                    <br>
                    <h3><strong>Paso 2</strong> - Formulario</h3>

                    <div class="pull-left">
                        <label class="label label-success">Seleccionar tabla</label>
                        <div id="<?php echo T6; ?>cont-tables" class="si-access" style="width: 200px;height: 426px;overflow: auto;">
                            <i class="fa fa-gear fa-3x fa-spin"></i>
                        </div>
                    </div>

                    <div class="pull-left" style="width: 80%;">
                        <label class="label label-success" style="margin-left: 10px;">Configurar campos</label>
                        <div id="<?php echo T6; ?>cont-columns" class="si-access" style="margin-left: 10px;height: 426px;">
                            <table id="<?php echo T6; ?>gridColumns" class="table table-bordered table-striped table-condensed table-hover smart-form has-tickbox">
                                <thead>
                                    <tr>
                                        <th style="width: 15%" class="center">Columna</th>
                                        <th style="width: 2%" class="center">Usar</th>
                                        <th style="width: 2%" class="center">Key</th>
                                        <th style="width: 8%" class="center">Id</th>
                                        <th style="width: 8%" class="center">Name</th>
                                        <th style="width: 20%" class="center">Etiqueta</th>
                                        <th style="width: 22%" colspan="2" class="center">Ayuda</th>
                                        <th style="width: 8%" class="center">Tipo</th>
<!--                                        <th style="width: 3%" class="center">Dependiente</th>
                                        <th style="width: 3%" class="center">Data</th>
                                        <th style="width: 3%" class="center">Validar</th>-->
                                    </tr> 
                                </thead>
                                <tbody id="<?php echo T6; ?>cont-columdas">
                                    <?php echo Functions::createCell(array('cells'=>8,'cols'=>9)) ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>











                <div class="tab-pane" id="tab3">
                    <br>
                    <h3><strong>Step 3</strong> - Data Grid</h3>
                    <div class="alert alert-info fade in">
                        <button class="close" data-dismiss="alert">
                            ×
                        </button>
                        <i class="fa-fw fa fa-info"></i>
                        <strong>Info!</strong> Place an info message box if you wish.
                    </div>
                    <div class="form-group">
                        <label>This is a label</label>
                        <input class="form-control input-lg" placeholder="Another input box here..." type="text" name="etc" id="etc">
                    </div>
                </div>
                <div class="tab-pane" id="tab4">
                    <br>
                    <h3><strong>Step 4</strong> - Save Form</h3>
                    <br>
                    <h1 class="text-center text-success"><strong><i class="fa fa-check fa-lg"></i> Completo</strong></h1>
                    <h4 class="text-center">
                        <button id="<?php echo T6; ?>btnCreaOpcion" type="button" class="btn btn-success btn-large" title="Crear Opción" onclick="opcion.postCrear(this);">    
                            <i class="fa fa-plus-circle fa-lg"></i>
                            Click aquí para crear y finalizar
                        </button>
                    </h4>
                    <br>
                    <br>
                </div>

                <div class="form-actions">
                    <div class="row">
                        <div class="col-sm-12">
                            <ul class="pager wizard no-margin no-border">
                                <!--<li class="previous first disabled">
                                <a href="javascript:void(0);" class="btn btn-lg btn-default"> First </a>
                                </li>-->
                                <li class="previous disabled">
                                    <a href="javascript:void(0);" class="btn btn-lg btn-default"> Anterior </a>
                                </li>
                                <!--<li class="next last">
                                <a href="javascript:void(0);" class="btn btn-lg btn-primary"> Last </a>
                                </li>-->
                                <li class="next">
                                    <a href="javascript:void(0);" class="btn btn-lg txt-color-darken"> Siguiente </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>

            </div>
        </div>
  
<?php echo Functions::widgetClose(); ?>
<script>
    $('.xhelp').tooltip({placement: 'right'});
    var $validator = $("#<?php echo T6; ?>formOpcion").validate({
        rules: {
<?php echo T6; ?>txt_opcion: {
                            required: true,
                            regular: true
                        },
<?php echo T6; ?>txt_prefijo: {
                            required: true,
                            regular: true,
                            rangelength: [3, 10]
                        }
                    },
                    highlight: function(element) {
                        $(element).closest('.form-group').removeClass('has-success').addClass('has-error');
                    },
                    unhighlight: function(element) {
                        $(element).closest('.form-group').removeClass('has-error').addClass('has-success');
                    },
                    errorElement: 'span',
                    errorClass: 'help-block',
                    errorPlacement: function(error, element) {
                        if (element.parent('.input-group').length) {
                            error.insertAfter(element.parent());
                        } else {
                            error.insertAfter(element);
                        }
                    }
                });

                var baseItemSelector = 'li:has([data-toggle="tab"])';
                $('#bootstrap-wizard-1').bootstrapWizard({
                    tabClass: 'form-wizard',
                    onTabClick: function(tab, navigation, index) {
                        //desactivar tabs
                        return false;
                    },
                    onTabChange: function(tab, navigation, index) {
                        if ($('#<?php echo T6; ?>rd_tipoB').is(':checked')) {
                            if (index == 3) {
                                navigation.find(baseItemSelector + ':eq(0) a').tab('show');
                            }
                        }
                    },
                    onNext: function(tab, navigation, index) {
                        var $valid = $("#<?php echo T6; ?>formOpcion").valid();
                        if (!$valid) {
                            $validator.focusInvalid();
                            return false;
                        } else {
                            /*validar tab 1*/
                            if(index === 1){
                                if ($('#<?php echo T6; ?>rd_tipoB').is(':checked')) {      /*si es BASICO*/
                                    /*se valida que opcion no se repita en modulo*/
                                    opcion.getUnique(navigation, baseItemSelector, index, 'B');
                                    return false;
                                } else if ($('#<?php echo T6; ?>rd_tipoM').is(':checked')) {  /*si es MANTENEDOR*/
                                    /*se valida que opcion no se repita en modulo*/
                                    opcion.getUnique(navigation, baseItemSelector, index, 'M');
                                    return false;
                                } else if ($('#<?php echo T6; ?>rd_tipoR').is(':checked')) {  /*si es REPORTE*/
                                    alert('Reporte en construccion');
                                    return false;
                                }
                            }
                            /*validar tab 2*/
                            if(index === 2){
                                
                                /*validar que este configurado los campos de formulario*/
                                var collection = $('#<?php echo T6; ?>gridColumns').find('tbody').find('tr');
                                var error = 1;
                                $.each(collection,function(){
                                    var usar = $(this).find('td:eq(1)').find('input:checkbox');
                                    var id   = $(this).find('td:eq(3)').find('input:text').val();
                                    var name = $(this).find('td:eq(4)').find('input:text').val();
                                    var etiq = $(this).find('td:eq(5)').find('input:text').val();
                                    if(usar.is(':checked') && id.length > 0 && name.length > 0 && etiq.length > 0){
                                        
                                        error = 0;
                                    }
                                });
                                
                                if(error === 1){
                                    simpleScript.notify.warning({
                                        content: 'Configure formulario'
                                    });
                                    return false;
                                }else{
                                    /*marca el paso como completado*/
                                    opcionScript.nextPaso('#bootstrap-wizard-1',index);
                                }
                            }
                        }
                    }
                });

                var wizard = $('.wizard').wizard();

                wizard.on('finished', function(e, data) {
                    //$("#fuelux-wizard").submit();
                    //console.log("submitted!");
                    $.smallBox({
                        title: "Congratulations! Your form was submitted",
                        content: "<i class='fa fa-clock-o'></i> <i>1 seconds ago...</i>",
                        color: "#5F895F",
                        iconSmall: "fa fa-check bounce animated",
                        timeout: 4000
                    });
                });
                /*para hacer evento invisible*/
                simpleScript.removeAttr.click({
                    container: '#<?php echo T6; ?>formOpcion',
                    typeElement: 'button'
                });
</script>
  </form>
</div>