<?php
/*
 * Documento   : nuevoModulo
 * Creado      : 08-ago-2014
 * Autor       : ..... .....
 * Descripcion : 
 */
$grabar = Session::getPermiso('CREMOGR');
?>
<form id="<?php echo T5; ?>formNuevoModulo" name="<?php echo T5; ?>formNuevoModulo" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php  echo LABEL_7; ?></h4>
            </div>
            <div class="modal-body smart-form">
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo LABEL_9; ?></label>
                        <div class="col col-10">
                            <label class="select"> 
                                <?php
                                    $data = moduloController::getAplicaciones();
                                    
                                    echo Functions::selectHtml(array(
                                        'data'=>$data,
                                        'atributes'=>array(
                                            'id'=>T5.'lst_aplicacion',
                                            'name'=>T5.'lst_aplicacion',
                                            'class'=>'form-control'
                                        ),
                                        'etiqueta'=>'aplicacion',
                                        'value'=>'id_aplicacion',
                                        'txtSelect'=>true
                                    ));
                                ?>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo LABEL_8; ?></label>
                        <div class="col col-10">
                            <label class="input"> 
                                <i class="icon-append fa fa-keyboard-o"></i>
                                <input type="text" id="<?php echo T5; ?>txt_descripcion" name="<?php echo T5; ?>txt_descripcion"></input>
                                <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo LABEL_DESC; ?></b>
                            </label>
                        </div>
                    </div>
                </section>
<!--                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo LABEL_14; ?></label>
                        <div class="col col-10 inline-group">
                            <label class="radio"> 
                                <input type="radio" id="<?php echo T5; ?>rd_dbS" name="<?php echo T5; ?>rd_db" value="S" checked>
                                <i></i>Si
                            </label>
                            <label class="radio"> 
                                <input type="radio" id="<?php echo T5; ?>rd_dbN" name="<?php echo T5; ?>rd_db" value="N">
                                <i></i>No
                            </label>
                        </div>
                    </div>
                </section>-->
            </div>
            <div class="modal-footer">
                <?php if ($grabar['permiso']): ?>
                    <button id="<?php echo T5; ?>btnGmodulo" type="submit" class="<?php echo $grabar['theme']; ?>">
                        <i class="<?php echo $grabar['icono']; ?>"></i> <?php echo $grabar['accion']; ?>
                    </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no riene permiso se anula submit desde cualquier input -->
<?php if (!$grabar['permiso']): ?>
    <script>
        simpleScript.noSubmit('#<?php echo T5; ?>formNuevoModulo');
    </script>
<?php endif; ?>
<script>
    $('.xhelp').tooltip({placement: 'right'});
    $('#<?php echo T5; ?>formNuevoModulo').validate({
        // Rules for form validation
        rules: {
            <?php echo T5; ?>lst_aplicacion: {
                required: true
            },
            <?php echo T5; ?>txt_descripcion: {
                required: true,
                regular: true,
                minlength: 3
            }
        },
        // Do not change code below
        errorPlacement: function(error, element) {
            error.insertAfter(element.parent());
        },
        submitHandler: function() {
            modulo.postNuevoModulo();
        }
    });
    /*para hacer evento invisible*/
simpleScript.removeAttr.click({
    container: '#<?php echo T5; ?>formNuevoModulo',
    typeElement: 'button'
});
</script>
