<?php
/*
 * Documento   : indexModulo
 * Creado      : 08-ago-2014
 * Autor       : ..... .....
 * Descripcion : 
 */
$grabar = Session::getPermiso('CREMONEW');
echo Functions::widgetOpen(array(
        'id'=>T5,
        'title'=>LABEL_6
    )); 
?>

    <div class="widget-body-toolbar"></div>
    <div class="dataTables_wrapper form-inline" role="grid">
        <div class="dt-top-row">
            <div class="DTTT btn-group">
                <?php if($grabar['permiso']): ?>
                <button id="<?php echo T5; ?>btnNew" type="button" onclick="modulo.getNuevoModulo(this);" class="<?php echo $grabar['theme']; ?>">
                    <i class="<?php echo $grabar['icono']; ?>"></i> <?php echo BTN_NUEVO; ?>
                </button>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <table id="<?php echo T5; ?>gridModulo" class="table table-striped table-bordered table-hover table-condensed" style="width:100%"></table>
<?php echo Functions::widgetClose(); ?>